name: CI-APP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Instalar dependências do sistema para Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk-bridge2.0-0 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libxss1 libasound2t64

      - name: Instalar dependências
        run: npm install
        working-directory: ./sgc-app

      - name: Rodar testes com coverage
        run: npx ng test --no-watch --code-coverage --browsers=ChromeHeadlessCI
        working-directory: ./sgc-app

      - name: Verificar coverage gerado
        run: |
          Get-ChildItem coverage -Recurse -ErrorAction SilentlyContinue
          if (Test-Path "coverage\lcov.info") {
            Write-Host "✅ lcov.info encontrado!"
            Get-Content coverage\lcov.info | Select-Object -First 5
          } else {
            Write-Host "❌ lcov.info NÃO encontrado"
            Write-Host "Arquivos na pasta coverage:"
            Get-ChildItem coverage -Recurse
          }
        working-directory: ./sgc-app
        shell: pwsh

      - name: SonarCloud Scan
        run: |
          npm install -D sonar-scanner
          npx sonar-scanner -Dsonar.token=$env:SONAR_TOKEN
        working-directory: ./sgc-app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}