name: CI-APP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'

      - name: Instalar dependências do sistema para Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk-bridge2.0-0 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libxss1 libasound2t64

      - name: Instalar dependências
        run: npm install
        working-directory: ./sgc-app

      - name: Rodar testes
        run: npm test -- --watch=false --browsers=ChromeHeadlessCI
        working-directory: ./sgc-app

      - name: Instalar sonar-scanner
        run: npm install -g sonar-scanner
        working-directory: ./sgc-app

      - name: Debug - Verificar valores SonarCloud
        run: |
          echo "SONAR_ORGANIZATION: $SONAR_ORGANIZATION"
          echo "SONAR_PROJECT_KEY: $SONAR_PROJECT_KEY"
          echo "SONAR_TOKEN: ${SONAR_TOKEN:0:10}..." # Mostra só os primeiros 10 chars por segurança
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}

      - name: SonarCloud Scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=$SONAR_ORGANIZATION \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.sources=src \
            -Dsonar.tests=src \
            -Dsonar.test.inclusions=**/*.spec.ts \
            -Dsonar.exclusions=**/node_modules/** \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.sourceEncoding=UTF-8
        working-directory: ./sgc-app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}